apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8083
        - containerPort: 8086
        - containerPort: 25826
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim0
        - mountPath: /usr/share/collectd/types.db
          name: influxdb-claim1
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
      - name: influxdb-claim1
        persistentVolumeClaim:
          claimName: influxdb-claim1
          readOnly: true
status: {}
