apiVersion: v2
name: sb-chart
description: A Helm chart for Surfboard Monitoring

type: application

version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: telegraf
    version: 1.7.23
    repository: https://helm.influxdata.com/
