# Default values for sb-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

telegraf:
  image:
    tag: "1.15"
  config:
    outputs:
      - influxdb:
          urls:
            - "http://first-post-influxdb:8086"
          database: "telegraf"
influxdb:
  image:
    tag: "1.8.0"
    pullPolicy: Always